### ISSUE TITLE
Gunpla Club Basic Modelling and Introduction

### ISSUE THREAD

**Issue by 9Breaker** [OpenSUTD/DiscoverSUTD-2021-microsite#103]
**Session Name**
Gunpla Club Basic Modelling and Introduction Workshop

**Abstract**

Gunpla Club is a plastic modelling club in SUTD. The club specialises in plastic models and welcomes all who enjoy plastic modelling, as well as improving members' maker skills and competencies with 3D printing and modelling.

**Student Organisation organising this session**
Gunpla Club

**Event Format**
Physical

**Session intent (what to expect)**

- Student participants will get to know more about Gunpla Club's activities and session timings.
- Student participants will get to learn the _basics of plastic modelling_, such as how to use cutters, how to file etc.
- Student participants will get to learn more about _3D printing basics_, _3D model preparation_, _basic 3D printing troubleshooting_.
- Student participants will get to learn more about _advanced additive manufacturing capabilities in SUTD_ by visiting DManD Centre (TBC)

**Session details**

Number of participants: 10-20 (Groups of max 4 due to SMM)
Location: Student Activity Centre (SAC), Think Tank 16/17/18, others TBC
Timing: 27th September 2021, 7-10pm

**Speakers/Workshop facilitators**

Speakers/Facilitators are Gunpla Club members and alumni who are passionate about plastic modelling and 3D printing.
They will share their experience with plastic modelling and 3D printing, especially their use in projects and the industry.
(Will include specific facilitators at a later date)

**Sign up link(if any)**
MS Forms Sign Up: https://forms.office.com/r/WTizk3RBNF
Workshop Telegram: https://t.me/joinchat/DT-hEwjySWBlZDk9

**Logistical details / Budget Needed**

Cutters: $2x20 - Aliexpress
Glass file: $2x20 - Aliexpress/Shopee
Filament: $20x5 - Shopee

Email: gunpla@club.sutd.edu.sg

**Comment by makehahaz** [comment]
Good day, thank you for your submission.

Could we check if there is a preferred date for your workshop? This will help with the booking of the venue.

**Comment by 9Breaker** [comment]
> Good day, thank you for your submission.
> 
> Could we check if there is a preferred date for your workshop? This will help with the booking of the venue.

Edited to include workshop date

**Comment by 9Breaker** [comment]
> Good day, thank you for your submission.
> 
> Could we check if there is a preferred date for your workshop? This will help with the booking of the venue.

Edited to include sign up link, telegram group link

**Comment by makehahaz** [comment]
Hi @9Breaker , just an update and some clarification from our team:

1. How many venues in total needed? Is one venue to host your 20 pax sufficient? 

2. TT16 and TT17 will not be available during the September term. So we're quite tight on venue space.

3. Where is the SAC located at, we are not sure if we have booking access to that venue.

Do update before this coming Wednesday, 25 Aug. Thank you!

**Comment by 9Breaker** [comment]
Hi @makehahaz ,

Apologies for the late reply. To address your queries:

1. We only require one venue. The above venues are suggestions as we understand that there is a chance that one of them might be occupied, therefore we put a few options that we are considering.

2. That is fine. Alternative suggestions are welcome.

3. The SAC (Student Activity Centre) is located at building 5 level 4. You do not need to book the venue for us, we can settle that on our end and drop OSL and email for access.

If anything requires urgent attention, you can drop me a pm on tele @NineBreaker

**Comment by castlemas** [comment]
Hi @Sorahawk ,
We will request a booking of TT18 for your event.

May I clarify that the 20 participants includes the number of facilitators too? If so, would it be possible to estimate the number of facilitators?

Would be great if you could let me know by today. I have dropped you a Telegram message too.

Thank you xx

**Comment by castlemas** [comment]
> Hi @9Breaker ,
> We will request a booking of TT18 for your event.
> 
> May I clarify that the 20 participants include the number of facilitators too? If so, would it be possible to estimate the number of facilitators?
> 
> Would be great if you could let me know by today. I have dropped you a Telegram message too.
> 
> Thank you xx

Replied via tele: total attendee would be 20 + 5/10facils 

Just an update, no actions required

**Comment by makehahaz** [comment]
Hi @9Breaker Just to update on 2 things:

1. Your budget has been approved. More details on the claim will be let known:
