### ISSUE TITLE
SUTD Archery - Induction Course

### ISSUE THREAD

**Issue by Sorahawk** [OpenSUTD/DiscoverSUTD-2021-microsite#104]
**Session Name**
SUTD Archery - Induction Course

**Abstract**
_Attending this induction course is necessary for students to participate in our regular weekly sessions._ They will be introduced to some basic archery theory, the safety aspects of shooting and shooting range procedures.

**Student Organisation organising this session**
SUTD Archery

**Event Format**
Physical

**Session intent (what to expect)**
Participants will not require any prior knowledge of archery. Participants of this induction course will be _allowed to attend future regular archery sessions_. The course will focus on some _basic archery theory, the safety aspects of shooting and shooting range procedures._

**Session details**
Date and Time: Friday, 1 Oct, 3-5pm
Venue: MPH (Have already checked and booked with Yuxin on this date and time)

Number of participants will have to depend on the maximum allowed by OSL after P2HA. Based on latest advisory before P2HA from OSL on 18 Jul, Archery was allowed to continue in groups of 5, up to 30 pax or venue capacity.

**Workshop facilitators**
Tan Le Xuan - President
Bridget Chua - Vice-President
Muhammad Hazmi - Captain
Ivan Tandyajaya - Logistics
Eliana Setiabudi - Publicity

**Sign up link**
https://forms.office.com/r/WpfytwkM7L

**Logistical details / Budget Needed**
$100 - Prizes (Archery equipment items)

Club Email: archery@club.sutd.edu.sg

**Comment by makehahaz** [comment]
Good day, unfortunately, the date of the session falls on the 1 October which is out of the DiscoverSUTD timeframe, hence we will not be able to support funding for your session.

**Comment by Sorahawk** [comment]
HI @makehahaz, thanks for clarifying, would just like to check: If we do not need funding, are we still able to tag this event under DiscoverSUTD, since it's just 1 day after the official end?

**Comment by makehahaz** [comment]
Hi @Sorahawk , just checked with the team that anything out of the 30 Sep range won't be tagged under DiscoverSUTD as the timeframe was given to all fifth rows. 

Hope your club understands that this is part of being fair to other fifth rows as well!

**Comment by Sorahawk** [comment]
Hi @makehahaz, we understand thanks for clarifying! I will close this issue since we won't be hosting the event under DiscoverSUTD
