### ISSUE TITLE
Students for the Exploration and Development of Space (SEDS-SUTD)

### ISSUE THREAD

**Issue by brutatoasta** [OpenSUTD/DiscoverSUTD-2021-microsite#107]
**Name of Student Organisation**
Students for the Exploration and Development of Space (SEDS-SUTD)

**Cluster**
Makers Cluster

**Classification**
Interest Group

**Description**
Advancing space technology and development through student-led, multi-disciplinary research, engineering and design projects.
We do chemical rockets, educational livestreams, and are looking to expand and do more projects. 

**Training / Meeting Timings**
Wednesday Afternoons

**Name / Contact of President**
Joshua Ng
Tele: @brutatoasta
Email: joshua_ngtzewee@mymail.sutd.edu.sg

**Other Relevant Links**
Tele: https://t.me/jhklsie 
IG: @seds_sutd
Twitch: https://www.twitch.tv/seds_sutd
Website: https://sedssutd.wixsite.com/info

**Comment by ExtremelySunnyYK** [comment]
Thanks Joshua for the submission of proposal!

**Comment by ExtremelySunnyYK** [comment]
Dear @brutatoasta Your event has been approved by the school admin. You have been allocated Music Room 1 on 24 Sep 3pm-6pm and 27 Sep 6pm - 9pm. The full $50 of requested budget has been approved as well.

Wishing you a smooth and successful event!
