### ISSUE TITLE
SUTD JUDO

### ISSUE THREAD

**Issue by sutdjudo** [OpenSUTD/DiscoverSUTD-2021-microsite#11]
**Name of Student Organisation**
SUTD JUDO

**Cluster**
Sports

**Classification**
Fifth Row 

**Description**
SUTD Judo club invites you to join us and learn some throws!

Judo - known as the gentle way, involves using the opponents force against themselves, using minimum effort to maximise efficiency. 

What can you expect? You can learn some self defense (throws and groundwork), acrobatics (rolling and cartwheels), and above all, have fun!

**Training / Meeting Timings**
Monday and Thursdays 7pm-10pm

**Student Organisation Introduction Video**
[https://youtu.be/X2cn43aFYtQ](url)

**Name / Contact of President**
Valerie Lu 
judo@club.sutd.edu.sg
Tele: @valubahloo

**Other Relevant Links**
Telegram group: [https://t.me/sutdjudo2021](url)
Instagram: [instagram.com/sutdjudo](url)

**Comment by ExtremelySunnyYK** [comment]
This is good
