### ISSUE TITLE
SUTD CDLH Introductory Session

### ISSUE THREAD

**Issue by ssjh23** [OpenSUTD/DiscoverSUTD-2021-microsite#112]
Session Name
Introductory session to CDLH

Abstract
DIY First Aid KIt and Basic First Aid

Student Organisation organising this session
Civil Defence LionHearters

Event Format
Physical

Session intent (what to expect)

At the end of the session, participants should be able to identify the basic items in a first aid kit and how to effectively use them, including bandaging and basic wound dressing.

No prerequisites required.

Session details
Number of participants expected: 10-15
Venue: Think Tank
Timing: 27 September 7.30 - 9pm

Speakers/Workshop facilitators
CDLH Members

Sign up link(if any)
NIL

Logistical details / Budget Needed

$100 for first aid kit contents

**Comment by jiayingpui** [comment]
Hi, here is the link for the compiled spreadsheet:

https://sutdapac-my.sharepoint.com/:x:/g/personal/cdlh_club_sutd_edu_sg/Edqjif5giFJHrtJdEWeTy_UBRhsHYzC0Dg25sf3y_4mxwA?e=7bSmg9

Our updated budget is approx $165.

**Comment by makehahaz** [comment]
Got it, thank you!

**Comment by castlemas** [comment]
Hi @jiayingpui  ,

May I clarify that the 15 participants include the number of facilitators too? If so, would it be possible to estimate the number of facilitators?

Would be great if you could let me know by today.

Thanks xx

**Comment by ssjh23** [comment]
Hi @castlemas,

Around 3 facilitators, included in the 15.

Thanks

**Comment by makehahaz** [comment]
Hi @ssjh23 . Not sure how your team wants to register the incoming freshies, if there is a need for a form, please do use this [form here](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPWH2rk0WPLpNoz88PwBGAxpUQ0c5TktQNlJKUTVMUFFQTVRHTkJOV1o1VS4u&sharetoken=zv60rxgRFw6Sp0GdVpWP) . Click on 'duplicate' and share with us your sign-up link here if needed!

**Comment by makehahaz** [comment]
https://forms.office.com/r/g6bXnNsjF1
