### ISSUE TITLE
SUTD  JUDO Introductory Session PLAN B

### ISSUE THREAD

**Issue by sutdjudo** [OpenSUTD/DiscoverSUTD-2021-microsite#113]
**SUTD JUDO Introductory Session**

**Abstract**

We will be conducting our Introductory Session externally at Jagsport (Judo Club), where participants can learn and try firsthand what Judo is all about.

**Student Organisation organising this session**
SUTD JUDO

**Event Format**
Physical 

**Session intent (what to expect)**

We hope our participants will gain an insight into how Judo is like as well as our SUTD JUDO community! 

We will meet at Upper Changi Mrt, commute together to Bendemeer Mrt and walk to Jagsport. 
By the end of the session, participants will know how to do break falls, rolls and basic judo techniques.

There is no need for a sports or martial arts background. 
Please come in comfortable sports attire! No shoes required.

**Session details**

Venue: Jagsport. 340-B King George's Ave King George's Building, 208574
No. of participants: 10 (tentatively) 
Date: Monday 20th September and Monday 27th September (2 Sessions) 
Time: TBC (1hr) 

**Speakers/Workshop facilitators**

Facilitators are experienced coaches from Jagsport judo club (https://jagsport.com) and SUTD Judo seniors.

**Sign up link(if any)**
https://forms.office.com/r/QKffrsLA7v

**Logistical details / Budget Needed**

No Budget Required.

**Comment by ExtremelySunnyYK** [comment]
Hi @sutdjudo thanks for submitting the event proposal.

Previously SUTD Judo has submitted another introductory session. May we know which would be the main session such that we are able to put on our website?

Thank you.

**Comment by sutdjudo** [comment]
Hi Yong Kang @ExtremelySunnyYK , we are unable to confirm at this point of time which one we will be doing (hence Plan A and Plan B) as we are currently sorting out some arrangements with OSL and external club. 

If there's a need to pick immediately, we could go ahead with PLAN A to be put up on the website. (The one which is conducted on campus with no body contact) 

Thanks! 
Valu, on behalf of SUTD Judo

**Comment by ExtremelySunnyYK** [comment]
Thank you Valu @sutdjudo ! We will keep that in mind. If there are any updates to which plan is preferred, do let us know over here!

**Comment by sutdjudo** [comment]
@ExtremelySunnyYK 

Will do! I believe I've been in contact with @castlemas on this as well. 

Thanks for your help and we apologise for the inconveniences!

**Comment by sutdjudo** [comment]
Hi @ExtremelySunnyYK We've been informed that we are now allowed to do contact training on campus. Hence we will be proposing an different Introductory Session from Plan A and Plan B (basically Plan B but hosted on campus). Do we need to make a new issue and redo a new proposal there or should we just write it here in the comments? Thanks!

**Comment by sutdjudo** [comment]
**SUTD JUDO Introductory Session**

**Abstract**

We will be conducting our Introductory Session on campus at Dance Studio 6 where participants can learn and try firsthand what Judo is all about!

**Student Organisation organising this session**
SUTD JUDO

**Event Format**
Physical 

**Session intent (what to expect)**

We hope our participants will gain an insight into how Judo is like as well as our SUTD JUDO community! 

By the end of the session, participants will know how to do break falls, rolls, basic judo throwing  and groundwork techniques.

There is no need for a sports or martial arts background. 
Please come in comfortable sports attire! No shoes required.

**Session details**

Venue: Dance Studio 6
No. of participants excluding Facilitator: 
10 participants (2 groups of 5) 
Date: Thursday, 16th September and Monday, 20th September
Time: 7pm-8pm and 8pm-9pm (Two sessions per day)

**Speakers/Workshop facilitators**

Facilitators are our very own experienced SUTD Judokas passionate in the sport and with competitive experience!

**Sign up link(if any)**
https://forms.office.com/r/QKffrsLA7v


**Logistical details / Budget Needed**

No Budget Required.

**Comment by sutdjudo** [comment]
Postponing physical session to Week 3 Monday and Thursday, if physical sessions are able to resume. We would like to wait for physical sessions to resume first, unless OSL does not allow us to do so for a longer period of time.
