### ISSUE TITLE
The Great IEEE-SUTD Challenge and Intro Session

### ISSUE THREAD

**Issue by kaveripriyap** [OpenSUTD/DiscoverSUTD-2021-microsite#116]
**Session Name**
The Great IEEE-SUTD Challenge 

**Abstract**
Introduction to the IEEE-SUTD Student Branch and the Executive Committee. Brief introduction to Arduino IDE and Arduino Uno microcontroller with a demonstration, ending with a mini-hackathon.

**Student Organisation organising this session**
IEEE-SUTD Student Chapter

**Event Format**
Virtual 

**Session intent (what to expect)**
- Participants are introduced to IEEE-SUTD Student Branch. Introduction to the executive committee of the club and their two cents about university life.
- Participants are introduced to the Arduino IDE and Arduino Uno Microcontroller. A demo of a basic circuit with some commonly used components can help understand the Arduino environment.
- Participants will take away a spirit of healthy competition in a fast paced session, with mystery rewards/prizes for their ideation and thinking process.
- Participants with little to no coding background also can participate in this workshop.

**Session details**
- Date: 17th September, 2021
- Time: 4:00 - 6:00 PM
- The workshop would begin with a brief introduction to IEEE and an encouraging talk from Prof. Pey Kin Leong (tentative appearance) yet to be confirmed.
- The workshop is organised as a challenge, the workshop facilitators would provide a brief introduction to the functioning of Arduino using Tinkercad, i.e., an alarm system using Arduino.
- We would then provide them with a challenge, i.e., a problem statement / design challenge.
- Teams would be made according to Arduino familiarity and then judged accordingly. 
- The top 3 innovative ideas using an Arduino board would win a reward (such as Gong Cha Voucher + IEEE Membership (tentative)).

**Speakers/Workshop facilitators**
- Professor Pey (subject to confirmation) - Associate Provost, Undergraduate Studies & SUTD Academy
- Kaveri Priya Putti: President of IEEE-SUTD
- Aishwarya Palaniappan: Vice-President of IEEE-SUTD
- Aum Bansal: Secretary of IEEE-SUTD
- Rohit Raghuram Murarishetty: Treasurer of IEEE-SUTD
- Visshal Natarajan - Technical Lead of IEEE-SUTD

**Sign up link (if any)**
https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPTwGWcshUepErjSBC4cJdD5UMDdRMktLNUhFMFUyR1laV0Q4Q1pHUzVCQS4u

**Logistical details / Budget Needed**
"Can Gong Cha vouchers be provided from DiscoverSUTD's budget? :)"
SGD $50 (IEEE membership + Gong Cha vouchers)
- Gong Cha Vouchers - $5 voucher (10 pcs - Top 2 teams - 5 members each) = $50
- We're planning on receiving free membership for some students from the parent IEEE organisation.

**Comment by ExtremelySunnyYK** [comment]
Hey @kaveripriyap, thank you for the clear details.
Could we trouble you to:
1. Put the date and timing of the session under the session details (understood that it is within your MS Form, but just to ensure people don't miss out on it) 
2. Give a breakdown for the budget required?Ho many vouchers and how much is the membership?
 E.g. [insert brand] chocolate, Qty and [link] if the item can be found online to justify the price. 


Do note that claims are done via concur with valid receipts required, so giving a clearer breakdown can facilitate a smoother process for budet approval. Cheers!

**Comment by kaveripriyap** [comment]
Hello, @ExtremelySunnyYK! I've updated the details according to the comments. Please do go through it and let me know if any changes need to be made. Cheers!

**Comment by ExtremelySunnyYK** [comment]
Dear @kaveripriyap Your event has been approved by the school admin. However no budget would be allocated as student admin is not able to fund individual membership.

Hope you understand and Wishing you a smooth and successful event!

**Comment by ExtremelySunnyYK** [comment]
Hey! Ieee has been allocated $50 bucks for the event!
