### ISSUE TITLE
SUTD Scratch! Intro Session 2021

### ISSUE THREAD

**Issue by FolkLoreee** [OpenSUTD/DiscoverSUTD-2021-microsite#117]
**Session Name**
DJ Crash Course by Scratch!

**Abstract**
Have you ever wanted to DJ but don't know where to start? 
Join us and discover how you can be a DJ!

**Student Organisation organising this session**
SUTD Scratch!

**Event Format**
Physical

**Session intent (what to expect)**

- Participants will learn the basics of _mixing_ music.
- Participants will familiarize themselves with _DJ equipment_.
- Participants will be exposed to _new genres_ of music.
- No pre-requisites needed!

**Session details**

No of participants: max 25 (5 groups of 5) + 5 exco members to facilitate.
Location: LT 5 or LT 4 (subject to availability)
Date/Time: Wednesday, 29th September 18.30 - 20.00

**Speakers/Workshop facilitators**

SUTD Scratch! Exco members :) 

**Sign up link(if any)**
https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPR24uD3WZ21BkLabbC4MqJJUQzVaOEdNRkw5TDQ2TUlBVlhKSk9KTzc0My4u

**Logistical details / Budget Needed**
None

Club Email: scratch@club.sutd.edu.sg

**Comment by ExtremelySunnyYK** [comment]
Hi @FolkLoreee thanks for submission of the event! do you guys need help booking the venue?

**Comment by FolkLoreee** [comment]
Hi @ExtremelySunnyYK, sure, would be great if you could help us book the venue. Thanks :)
But do let us know if you have any difficulty in booking since we usually do our own booking 😄

**Comment by ExtremelySunnyYK** [comment]
Hey @FolkLoreee  Just some feedback from our team that for your sign-up form. Do use the DiscoverSUTD form template which includes the PDPA clause. We are not able to verify as we cannot access your forms.

The link can be found here 
https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPWH2rk0WPLpNoz88PwBGAxpUQ0c5TktQNlJKUTVMUFFQTVRHTkJOV1o1VS4u&sharetoken=zv60rxgRFw6Sp0GdVpWP

Do click on 'duplicate form' and create your own form! Then share with use the updated link.

Hope your team understands, thank you!

**Comment by ExtremelySunnyYK** [comment]
Dear @lowryan Your event has been approved by the school admin. You have been allocated LT 4
29 Sep 6.30pm - 8pm.
Wishing you a smooth and successful event!

**Comment by lowryan** [comment]
Hi @ExtremelySunnyYK I think you've tagged the wrong person for this session

**Comment by caramelmelmel** [comment]
Our apologies! @lowryan 
@FolkLoreee your event has been approved! you can go ahead and make arrangements!!!

**Comment by caramelmelmel** [comment]
@ExtremelySunnyYK I have helped you to check lmk if you need to open this issue up again

**Comment by makehahaz** [comment]
Hi @FolkLoreee Your sign-up form seems to be broken. Could I trouble you to look into the link and re-upload the sign-up form once more? Thank you!

**Comment by FolkLoreee** [comment]
Hi @makehahaz @ExtremelySunnyYK, sorry, we attached the wrong link.
I have amended the link to point to the correct form.
We duplicated the form off your template earlier, and from what I see, the PDPA clause is still there.
Is there any part in particular that we need to change?

**Comment by makehahaz** [comment]
@FolkLoreee All is well! The venue should be LT4 for your planned session. Cheers!
