### ISSUE TITLE
SUTD Ultimate Frisbee

### ISSUE THREAD

**Issue by makehahaz** [OpenSUTD/DiscoverSUTD-2021-microsite#12]
**Name of Student Organisation***
Ultimate Frisbee

**Cluster**
Sports

**Classification**
Fifth Row

**Description**
A family running and chasing after discs together. We welcome Frisbee players of all skill levels to join us; from training to just having fun together, the Ultimate Club goes far together.

**Training / Meeting Timings**
Competitive team: Wednesdays 1930 - 2230
Recreational: Fridays 1600 - 1900

**Student Organisation Introduction Video**
[Promotional Video](https://www.youtube.com/watch?v=mPH2AcaS95k)

**Name / Contact of President**
Tan Jia Yue / @tanjiayue (Telegram)

**Other Relevant Links**
[Instagram](https://www.instagram.com/sutdultimate/)

**Comment by ExtremelySunnyYK** [comment]
This is good!
