### ISSUE TITLE
IES: The Coding Tournament 

### ISSUE THREAD

**Issue by kaveripriyap** [OpenSUTD/DiscoverSUTD-2021-microsite#129]
**Session Name**
IES: The Coding Tournament 

**Abstract**
The Coding Tournament is a programming competition organized by IES-SUTD. It aims at stimulating students' programming creativity and improving their coding ability. Further, it also aims to provide students a window into what being a IES member entails.

**Student Organisation organising this session**
IES-SUTD Student Chapter

**Event Format**
Virtual

**Session intent (what to expect)**
- Participants are introduced to IES-SUTD Student Branch and to the Executive Committee of the club.
- Participants are introduced to the coding tournament and will take away a spirit of healthy competition in a fast paced session, with mystery rewards/prizes for their ideation and thinking process.
- Participants with basic coding background can participate in this workshop.
- Participants can expect a challenging tournament where they can solve and create computer problems (like algorithm problems).

**Session details**
- Date: September 24th 2021
- Time: 7:00 - 10:00 PM
- The session involves a coding tournament by segregating players into teams based on their coding familiarity.
- The teams are given 2 challenges worth 100 points each and the teams are awarded points based on their time of completion. 
- For the next round, each team is required to come up with a computing problem along with a solution and assign some point value to it (max - 100).
- The teams are then paired with another team and they try to solve the other team's coding problem.
- The kick in this round comes from the fact that the team can assign points to their problem based on their confidence level. If they are confident about the problem then they can assign 100 points for solving the problem and if the opposing team solves the problem, then the opposing team acquires the 100 points and the team which created the problem loses 100 points.
-  Subsequently in the next team pairing, they can choose to reduce the value of their problem to 50 points. In the event that the opposing team fails to solve the problem, then the challenging team would acquire the 100 points that they assigned to the problem.
- At the end of the competition, the top 3 teams win prizes/rewards.
- The contest would be hosted on HackerRank. 

**Speakers/Workshop facilitators**
- Dr. Teo Tee Hui: Senior Lecturer and IES-SUTD Student Chapter Advisor (tentative)
- Visshal Natarajan: President of IES-SUTD
- Jerry Feng Zhuoer: Vice-President of IES-SUTD
- Kaveri Priya Putti: Secretary of IES-SUTD
- Siqi Xiang: Treasurer of IES-SUTD
- Wang Yanbao: Outreach Director of IES-SUTD

**Sign up link (if any)**
https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPe9AkARfAURCtSLMDgWfoFdUMTJWOTg4Q09KMEIwVEE2M0xFSEVNR0VLQS4u

**Logistical details / Budget Needed**
SGD $120 (top 3 prizes)
- $10/shirt for the top 3 teams (3 members/team)
- Printed IES T-shirt from Meow Print (https://meowprint.sg/blog/printing-services-sunshine-plaza-singapore/)
- $30 popular voucher for the top team

**Comment by makehahaz** [comment]
Hey @kaveripriyap, thank you for the clear details. 

Could we trouble you to:
1. Put the date and timing of the session under the session details (understood that it is within your MS Form, but just to ensure people don't miss out on it)

2. Give a breakdown for the budget required? Like what sort of prizes are you looking to give away? 
E.g. [insert brand] chocolate, Qty and [link] if the item can be found online to justify the price.

Do note that claims are done via concur with valid receipts required, so giving a clearer breakdown can facilitate a smoother process for budet approval. Cheers!

**Comment by makehahaz** [comment]
Hi @kaveripriyap , do let us know on the budget breakdown for your event. 

Do get back with the breakdown by this Wednesday, 25 August, with the requested information.

**Comment by kaveripriyap** [comment]
Hello, @makehahaz! I've updated the details according to the comments. Please do go through it and let me know if any changes need to be made. Cheers!

**Comment by castlemas** [comment]
Update:

As communicated over Telegram,
Time is shifted to **3:00 pm - 6:00pm** on **24/9**

(no actions needed, just an update)
