### ISSUE TITLE
AISG-SUTD

### ISSUE THREAD

**Issue by Anirudh181001** [OpenSUTD/DiscoverSUTD-2021-microsite#13]
**Name of Student Organisation***
AISG-SUTD

**Cluster**
Makers Cluster

**Classification**
Interest Group

**Description**
We are AISG-SUTD. Our activities are manifold, including but not limited to technical workshops, bonding sessions, industry talks and visits, project initiations, research activities etc. Our club events are sure to be creative, interesting and well-thought out. The various activities of our club will integrate design and technology, and will serve to improve and uphold the vision and maker culture in SUTD. Projects and workshop activities will promote interaction between students of different pillars, batches, and various staff and faculty members, thereby bringing a close knit AI community in our school to allow interdisciplinary projects  which integrate the use of artificial intelligence to take place.

**Training / Meeting Timings**
Event-by-event basis

**Student Organisation Introduction Video**
NA

**Name / Contact of President**
Anirudh Shrinivason anirudh_shrinivason@mymail.sutd.edu.sg / @Anirudh181001

**Other Relevant Links**
Discord: https://discord.gg/JF9XVv9F (Expires every 7 days)
Telegram: https://t.me/joinchat/zhmpV91-7AsyMzQ9
Instagram: https://www.instagram.com/aisg.sutd/
Linkedin: https://www.linkedin.com/company/aisgsutd/

**Comment by ExtremelySunnyYK** [comment]
This is good!
