### ISSUE TITLE
Esports intro session

### ISSUE THREAD

**Issue by Ho0M4n** [OpenSUTD/DiscoverSUTD-2021-microsite#135]
**Session Name**
Esports intro session

**Abstract**
SUTD Esports games night for new and current members, _join pls, can derp around or tryhard, everything also can_
feeders also welcome

**Student Organisation organising this session**
SUTD Esports

**Event Format**
Virtual

**Session intent (what to expect)**
Participants will learn about the Esports club and the stuff we do
also to have fun :3
or to tryhard if they want to

Games that will be played
- League of Legends
- Valorant
- any game that has sufficient players on that day

**Session details**
18 Sept 2021 (Saturday) 9pm - 11pm
25 Sept 2021 (Saturday) 9pm - 11pm
2 Aug 2021 (Saturday) 9pm - 11pm
Will be held on SUTD Esports Discord

**Speakers/Workshop facilitators**
Facilitators will be the current exco

**Sign up link(if any)**
Link to join SUTD Esports Discord
https://discord.gg/GDhntdUmzm 

**Logistical details / Budget Needed**
Nothing
Club email
esports@club.sutd.edu.sg

**Comment by ExtremelySunnyYK** [comment]
Approved! Thanks @Ho0M4n
