### ISSUE TITLE
Introduction to Data Visualization (AISG-SUTD)

### ISSUE THREAD

**Issue by Anirudh181001** [OpenSUTD/DiscoverSUTD-2021-microsite#14]
**Session Name**
Introduction to Data Visualization

**Abstract**
Participants will get a brief introduction into the world of data analysis and visualization, and will get hands on experience to work on tools such as SQL and Tableau!

**Student Organisation organising this session**
AISG-SUTD

**Event Format**
Physical

**Session intent (what to expect)**

- Participants will learn the basics of data analysis and visualization with SQL and Tableau
- Curiosity to learn
- _SQL, Tableau and Data visualization techniques_

**Session details**
Maximum participants: 50 (Subject to change based on several unprecedented factors)
Location: Think Tank 8/9.
Timing: >6pm
We would like to seek help to book the location for the purpose of the event!

**Speakers/Workshop facilitators**

Anirudh Shrinivason: President of AISG-SUTD; Penultimate year CSD student
Dhanush Manogar: Vice President of AISG-SUTD; Freshmore student
Sahana Katragadda: Secretary of AISG-SUTD; Freshmore student
Jeff Lai Pin Nean: Treasurer of AISG-SUTD; Freshmore student

**Logistical details / Budget Needed**
Mini oreo packets: $28.3 for 36 packets https://www.roundeyesupply.com/Mini-White-Creme-Chocolate-Sandwich-Cookies-3-Oz-p/de460590.htm
Milo tetra pack drink: $13.5 for 24 packets https://shopee.sg/MILO-UHT-Activ-Go-200ml-(Bundle-of-12-24-packs)-i.399307639.11207651362?position=6
Number of attendees: 20 freshies+ 4 facilitators.
Cost per person: $1.67
Total cost: $41.8
Justification: We would like to get a budget to source snacks to engage participants further for the workshop. Moreover, since the workshop is taking place in the evening, after a long day, participants will be motivated by some light snacks too. The workshop can be mentally and intellectually stimulating. And as it is said, "A full stomach is a full mind", we would like our participants to be in with a full mind. Thus, we feel that providing some snacks would greatly enhance the experience of the workshop for them.

Email ID: anirudh_shrinivason@mymail.sutd.edu.sg / dhanush_kumar@mymail.sutd.edu.sg
Form Link: https://forms.office.com/Pages/DesignPage.aspx#FormId=drd2NJDpck-5UGJImDFiPbAE8J5NASpDrs2cVRnSweJUM0o5N0c4OTVJMzQ5TFVaODBXNDEyU05LNi4u

**Comment by ExtremelySunnyYK** [comment]
Hey AISG! thanks for submitting the proposal. I have 2 questions for the event.
1. How much budget do you need and what would the breakdown of the budget look like?
2. How will participants be spaced apart in groups?

Thanks!

**Comment by Anirudh181001** [comment]
> Hey AISG! thanks for submitting the proposal. I have 2 questions about the event.
> 
> 1. How much budget do you need and what would the breakdown of the budget look like?
> 2. How will participants be spaced apart in groups?
> 
> Thanks!

1. Budget: $300 ($5 / participant). $4 for some snacks (ie: sandwich and a piece of cake) and $1 for a drink
2. 4 participants per table. (Subject to regulations)

**Comment by jolow99** [comment]
Hi @Anirudh181001 thanks for getting back. Just wanted to get a bit more detail from you so that we can increase the chances of your event getting funded. 

1. Could we get a specific date / time / duration for your event? 
2. Could you provide the specific breakdown of the snacks you would be purchasing, an estimated number of attendees and a short justification for it? 

I do recommend that you purchase snacks in bulk and possibly reduce the requested cost per person in order to increase your chances, as it does seem to be a bit on the high side relative to other fifth rows. 

Thanks for understanding!

**Comment by Anirudh181001** [comment]
> Hi @Anirudh181001 thanks for getting back. Just wanted to get a bit more detail from you so that we can increase the chances of your event getting funded.
> 
> 1. Could we get a specific date / time / duration for your event?
> 2. Could you provide the specific breakdown of the snacks you would be purchasing, an estimated number of attendees and a short justification for it?
> 
> I do recommend that you purchase snacks in bulk and possibly reduce the requested cost per person in order to increase your chances, as it does seem to be a bit on the high side relative to other fifth rows.
> 
> Thanks for understanding!

1. 29th September 6pm-8pm
2.  Ahh okay. How about $150 for everyone, and we will provide a pack of chips and a drink instead? Is this better?
Thanks!

**Comment by Anirudh181001** [comment]
> > Hi @Anirudh181001 thanks for getting back. Just wanted to get a bit more detail from you so that we can increase the chances of your event getting funded.
> > 
> > 1. Could we get a specific date / time / duration for your event?
> > 2. Could you provide the specific breakdown of the snacks you would be purchasing, an estimated number of attendees and a short justification for it?
> > 
> > I do recommend that you purchase snacks in bulk and possibly reduce the requested cost per person in order to increase your chances, as it does seem to be a bit on the high side relative to other fifth rows.
> > Thanks for understanding!
> 
> 1. 29th September 6pm-8pm
> 2. Ahh okay. How about $150 for everyone, and we will provide a pack of chips and a drink instead? Is this better?
>    Thanks!

Hi Joseph, Regarding the budget breakdown:
1. Mini oreo packets: $28.3 for 36 packets https://www.roundeyesupply.com/Mini-White-Creme-Chocolate-Sandwich-Cookies-3-Oz-p/de460590.htm
2. Milo tetra pack drink: $13.5 for 24 packets https://shopee.sg/MILO-UHT-Activ-Go-200ml-(Bundle-of-12-24-packs)-i.399307639.11207651362?position=6

Number of attendees: 20 freshies+ 4 facilitators.
Cost per person: $1.67
Total cost: $41.8
Justification: We would like to get a budget to source snacks to engage participants further for the workshop. Moreover, since the workshop is taking place in the evening, after a long day, participants will be motivated by some light snacks too. The workshop can be mentally and intellectually stimulating. And as it is said, "A full stomach is a full mind", we would like our participants to be in with a full mind. Thus, we feel that providing some snacks would greatly enhance the experience of the workshop for them.

**Comment by ExtremelySunnyYK** [comment]
@Anirudh181001 for the timing of the booking of think thank, would 6-9 pm be an okay timing?

**Comment by Anirudh181001** [comment]
Yup sure that sounds good!

**Comment by castlemas** [comment]
Hi @Anirudh181001 ,

The registration form link you provided requires permission, could you send us one where everyone could access?

Thank you xx

**Comment by jolow99** [comment]
Hi @Anirudh181001 Your event has been approved by the school admin. 

You have been given TT23 which has a capacity of 25 pax, on 29 Sep from 6pm-8pm. 

Additionally, your budget request of $41.80 has been allocated $32.40 as refreshment claims are capped at $1.35 per pax. 

Wishing you a smooth and successful event!

**Comment by Dhanushkmr** [comment]
@jolow99 @castlemas  Here is the link to the form: https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPbAE8J5NASpDrs2cVRnSweJUM0o5N0c4OTVJMzQ5TFVaODBXNDEyU05LNi4u

**Comment by caramelmelmel** [comment]
@Dhanushkmr noted for that!
