### ISSUE TITLE
SOAR Tea Session

### ISSUE THREAD

**Issue by iangohy** [OpenSUTD/DiscoverSUTD-2021-microsite#144]
**Session Name**
SOAR Tea Session

**Abstract**

Introduction to what we do and who we are here at SOAR (SUTD Organization of Autonomous Robotics)! An introductory session where every SOAR project can be  showcased in detail. Participants can sign up for SOAR challenge here too,  which is an introductory program to become an official SOAR member.  

**Student Organisation organising this session**
SUTD Organization of Autonomous Robotics

**Event Format**
Physical

**Session intent (what to expect)**

- Know what SOAR does
- Introduction to ongoing projects in SOAR
- Connect with current SOAR members
- Be inspired by current projects

**Session details**

Max number of participants: 35 per session x 2 = 70 total.

Date: 

* 16 September 2021

* Session 1: 1930 - 2030

* Session 2: 2100 - 2200

Location: TT16/17

Participants will be in groups of 5 and will not intermingle between groups during the session.

*Session flow*

Introduction to SOAR (Presentation style - 20 min)

Projects showcase (10 min each x 4 projects)

* Projects will be set up at the corners of the combined Think Tanks
* At each project, there will be a maximum of 2 groups of 5 safely distanced from each other
* Every 10 minutes, participants will move to the next project

**Speakers/Workshop facilitators**

Current exco and project members in SOAR

**Sign up link(if any)**
https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPZ0x4lBoJ0FJp4ph0q2ywpVUMUVQUlhJRTI2T1Y1OExTTkM4WVY0NzQyWi4u

**Logistical details / Budget Needed**

Club email: soar@club.sutd.edu.sg

**Comment by ExtremelySunnyYK** [comment]
@iangohy Thanks for submitting the event for soar!
The question from student admin is:
TT 16/17 will not be available for Sep term. There are limited venues that can accommodate up to 35pax. Would the club consider to reduce expected attendees to 25pax instead and I will check for venue availablity when the booking system is ready?

**Comment by iangohy** [comment]
Hi! Noted that TT 16/17 is not available. Could you help us to check if it is possible to book two think tanks (near or adjacent to each other)? If possible, we can split our 4 project showcase into 2 projects per think tank. Thanks!

**Comment by castlemas** [comment]
@iangohy 

Hi there, below are the venues and times that we could help book for. Would be great if you could let me know by today.

**Only the following venues are able to accommodate 35pax.
 - TT 9/10 are available after 8pm on 16 Sep.
 - Would the club consider LT 5 instead? Maximum capacity for LT 5 with 'W" seating pattern is 48pax**

Do let me know if you have any questions.

Thank youxx

**Comment by castlemas** [comment]
Updates:
SOAR will be requesting for booking of LT 5 48pax

(just an update, no actions required !!)

**Comment by castlemas** [comment]
Hi @iangohy ,

May I clarify that the 48 pax includes the number of facilitators too? If so, would it be possible to estimate the number of facilitators?

Would be great if you could let me know by today.

Thank you xx

**Comment by iangohy** [comment]
Hi @castlemas,

Yup, the 48 pax will include the facilitators (13 pax). Thanks!

**Comment by ExtremelySunnyYK** [comment]
Dear @iangohy Your event has been approved by the school admin. You have been allocated

LT5
16 Sep 7.30pm - 10pm


Wishing you a smooth and successful event!

**Comment by iangohy** [comment]
Hi @ExtremelySunnyYK,

We have some freshmore messaging us saying that they wouldn't be in Singapore in time. Can we check if we want to livestream our tea session do we need any extra forms or anything? The livestream will only include the soar hosts, no participants.

Thanks!

**Comment by jolow99** [comment]
@iangohy 

Hey Ian! 

No worries on that, but do make it clear in the registration form for registrants who won't be attending physically. 

All the best!
