### ISSUE TITLE
Energy Club

### ISSUE THREAD

**Issue by yenchingp** [OpenSUTD/DiscoverSUTD-2021-microsite#16]
**Name of Student Organisation***
Energy Club

**Cluster**
Makers

**Classification**
Fifth Row

**Description**
Our club aims towards clean and sustainable energy by educating our members and fellow peers on ways to incorporate them into their work through thinking, prototyping and fabricating sustainable solutions for modern day problems. Our work vary from long term projects to conducting TinkerDay Workshops for the student population.

**Training / Meeting Timings**
Event-by-event basis

**Name / Contact of President**
Phua Yen Ching (yenching_phua@mymail.sutd.edu.sg) 

**Other Relevant Links**
Telegram: https://t.me/joinchat/H3dY-xeG78ZME3ZzLiWwyg
Email: energy@club.sutd.edu.sg
Instagram: sutd_energyclub

**Comment by ExtremelySunnyYK** [comment]
This is good!
