### ISSUE TITLE
Pandemic! At The Disco 2.0

### ISSUE THREAD

**Issue by caydennn** [OpenSUTD/DiscoverSUTD-2021-microsite#17]
**Session Name**
Pandemic! At The Disco 2.0

**Abstract**
Pandemic! At The Disco 2.0 is the second rendition of our Pandemic! online concert series, whereby SUTD Bands members and alumni record their favorite songs and showcase their talents in their homemade music videos. 

**Student Organisation organising this session**
SUTD Bands

**Event Format**
Virtual YouTube Premiere

**Session intent (what to expect)**
Entertainment and enjoy performances by the best of SUTD Bands. 
Key takeaway: A good time :) 

**Session details**
18th September
Timing : 7-9
Held virtually
Link to video will be updated on our [link tree ](https://linktr.ee/sutdbands)

**Logistical details / Budget Needed**
NIL

Club Email Address: sutdbands@club.sutd.edu.sg

*We have submitted our EPF to OSL already and has been approved.

**Comment by ExtremelySunnyYK** [comment]
@caydennn any updates to the timing?

**Comment by ExtremelySunnyYK** [comment]
Hey @caydennn Just some feedback from our team that for your sign-up form. Do use the DiscoverSUTD form template which includes the PDPA clause. We are not able to verify as we cannot access your forms.

The link can be found here
https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPWH2rk0WPLpNoz88PwBGAxpUQ0c5TktQNlJKUTVMUFFQTVRHTkJOV1o1VS4u&sharetoken=zv60rxgRFw6Sp0GdVpWP

Do click on 'duplicate form' and create your own form! Then share with use the updated link.

Hope your team understands, thank you!

**Comment by caydennn** [comment]
Time updated to 7pm. 
Get back to you on the form.

**Comment by caydennn** [comment]
Hi. You can ignore the sign up form already since we have already closed sign ups. We have the bands performing already. We just need this event on the DiscoverSUTD Calendar. Thanks.
