### ISSUE TITLE
Taal Intro Session

### ISSUE THREAD

**Issue by namitha9** [OpenSUTD/DiscoverSUTD-2021-microsite#175]
**Session Name**
Taal Intro Session

**Abstract**

A session to introduce the freshies to the bollywood dance culture and welcoming them to the family with fun games and Simpang supper. 

**Student Organisation organising this session**
Taal Indian Dance Club

**Event Format**
Physical

**Session intent (what to expect)**

- Share with us what you hope your participants will take away from this session (Participants will learn ...)
We hope the new participants can familiarise themselves with a new bollywood dance choreography and help them feel comfortable with the dance culture. 

- Share with us if there are any prerequisites to make the most of this session (Participants will require knowledge of ...)
Just wear comfortable clothes 

- *italicise* the specific skills/ takeaways that are quantifiable to help us create a concept map of the sessions we are offering for our incoming Freshmores
New Bond
Dance
Fun

**Session details**

No of participants per session : 1-2 instructors, 2-4 exco, 10-15 participants 
Venue : Dance Studio 1
Dates: 14th and 16th September
Timing: 7:00pm - 9:00pm

**Speakers/Workshop facilitators**
Session will be held by:
K Sangavi (T3, Vice-President) on 14th and 16th September
Vedika Sairam Poonamalle (T3, Publicity Head) on 14th September
Chirag Shivakumar (T3, Secretary) on 16th September
Saakshi Vinod Saraf (T3, Dance Captain) on 14th and 16th September

**Sign up link(if any)**
[Insert Signup Link]

**Logistical details / Budget Needed**
Total: $14
(First-Aid Kit)

Help us with the overall resourcing of our events. This will give us a cue as to how to budget for the event and if there are further constraints we must consider.
Please provide us with your club e-mail address so we can notify you once your event has been scheduled. 
taal@club.sutd.edu.sg

**Comment by caramelmelmel** [comment]
Hi @namitha9 I believe that @castlemas has already replied to this on telegram. As you have submitted it very late, we cannot process this event.
