### ISSUE TITLE
SUTD Bands Bandscamp 2021

### ISSUE THREAD

**Issue by caydennn** [OpenSUTD/DiscoverSUTD-2021-microsite#24]
**Session Name**
Bandscamp

**Abstract**
An online bands camp organized by SUTD Bands to orientate the freshies and share with them more about our club. They will also get a chance to get their hands dirty working on a music project.

**Student Organisation organising this session**
SUTD Bands

**Event Format**
Virtual

**Session intent (what to expect)**
To introduce SUTD Bands to incoming freshies (Eg. what the club is about, the events we organize) and to try to orientate potential club members
*Creativity*
*Teamwork*

**Session details**
25th September, 2-6pm
Link to Telegram group for interested freshies to be found in the form (Zoom link will be posted there)

**Speakers/Workshop facilitators**
NIL - SUTD Bands Exco 

**Sign up link(if any)**
https://forms.office.com/r/5YpxEkdLfT

**Logistical details / Budget Needed**
NIL

Please provide us with your club e-mail address so we can notify you once your event has been scheduled. 
sutdbands@club.sutd.edu.sg

Copy this [template](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPWH2rk0WPLpNoz88PwBGAxpUQ0c5TktQNlJKUTVMUFFQTVRHTkJOV1o1VS4u&sharetoken=zv60rxgRFw6Sp0GdVpWP) to ensure consistent branding throughout DiscoverSUTD.

**Comment by ExtremelySunnyYK** [comment]
Event Approved! Congrats and hope you guys have a great event!
