### ISSUE TITLE
Rotaract Introductory Session

### ISSUE THREAD

**Issue by rotaractsutd** [OpenSUTD/DiscoverSUTD-2021-microsite#34]
**Session Name**
Rotaract Introductory Session

**Abstract**
Have a passion to serve the community? Want to use your talents and skills to make a difference? Get to know what SUTD Rotaract has in store for you during this Introductory Session!

**Student Organisation organising this session**
Rotaract Club

**Event Format**
Virtual

**Session intent (what to expect)**
- Participants will get to learn more about the volunteering, event planning and leadership opportunities that Rotaract Club offers, as well as how Rotaract Club continued serving the community amidst the COVID-19 pandemic. 
- Everyone is welcome to this Introductory Session and no prior knowledge is required! Join us to find out how we can change the community together!

**Session details**
Date: Monday, 20 September 2021
Time: 1930 - 2030
Venue: MS Teams (https://tinyurl.com/32s4ch9c), link will be sent out again via email closer to date to confirm attendance
No. of participants: NO LIMIT

**Speakers/Workshop facilitators**
SUTD Rotaract EXCO Members

**Sign up link(if any)**
https://forms.office.com/r/nME4YR4zx4

**Logistical details / Budget Needed**
No budget required.

Club Email: rotaract@club.sutd.edu.sg
Telegram Group Link: https://t.me/joinchat/IkywE0yhCsrdykbptliO7A

**Comment by jolow99** [comment]
Dear @rotaractsutd Your event has been approved by the school admin. Wishing you a smooth and successful event!
