### ISSUE TITLE
Changi Coffee Corner 

### ISSUE THREAD

**Issue by jolow99** [OpenSUTD/DiscoverSUTD-2021-microsite#4]
**Name of Student Organisation***
Changi Coffee Corner

**Cluster**
Specialist

**Classification**
Interest Group

**Description**
Through building a vibrant coffee brewing culture in SUTD, Changi Coffee Corner hopes to connect people over coffee and build the community. With our goal of having a student-run espresso coffee cart, we are limited to conduct internal workshops and coffee appreciation sessions for our members. Do join us if you have a passion for coffee and would like to be a part of our community.

**Training / Meeting Timings**
TBC

**Student Organisation Introduction Video**
N.A

**Name / Contact of President**
Joseph Low 
Telegram: @jolow

**Other Relevant Links**
Join our Telegram group at https://t.me/joinchat/Uxk-Q-j-MC71VPSd

**Comment by ExtremelySunnyYK** [comment]
This is good.
