### ISSUE TITLE
Uni-Y Welcome Tea [Community Service Club]

### ISSUE THREAD

**Issue by ongkahyuan** [OpenSUTD/DiscoverSUTD-2021-microsite#44]
​​**Session Name**
Uni-Y Welcome Tea

**Abstract**
Uni-Y Welcome Tea is a time for us to show you how you can serve the community as a SUTDent! Through this event, we also hope to introduce you to our Uni-Y fam - who’ll answer any lingering questions about uni and settling into a new phase of life :) 

**Student Organisation organising this session**
University-YMCA (Uni-Y)

**Event Format**
Virtual, on Zoom.

**Session intent (what to expect)**
- Participants will learn more about university life, including tips that Uni-Y seniors will share about adjusting to university life in SUTD. Additionally, participants will also learn more about Uni-Y as a community service club and the many activities that we organise to the wider SUTD community, Singapore social community, and overseas community.
- Participants will not need any prior knowledge to join this event.
- A better understanding of university life and of Uni-Y as a community service club.

**Session details**
This event will be held entirely online, via Zoom. We aim to have at least 25 attendees joining us for this Uni-Y Welcome Tea event.

Date: 17 September 2021, Friday
Time: 3 pm - 4:45 pm
Venue: Zoom
Duration of event: 1 h 45 min

**Speakers/Workshop facilitators**

Uni-Y Exco
**Sign up link(if any)**
https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPU5uKUNjBNRFlv8MT4i8IpVUQ0hWOTAxNkNTRTlHM1VQOVNCMDlLTDVXQy4u

**Logistical details / Budget Needed**

No funding is required. Funding will come from YMCA.
Club email is: uni_y@club.sutd.edu.sg

**Comment by jolow99** [comment]
Dear @ongkahyuan Your event has been approved by the school admin. Wishing you a smooth and successful event!
