### ISSUE TITLE
SUTD Archery

### ISSUE THREAD

**Issue by Sorahawk** [OpenSUTD/DiscoverSUTD-2021-microsite#48]
**Name of Student Organisation**
SUTD Archery

**Cluster**
Sports

**Classification**
Fifth Row

**Description**
SUTD Archery aims to allow all students to try out, or even pick up, archery as a sport here in SUTD! We provide an outlet for students to relax and shoot after a hectic day at school.

We welcome anyone regardless of prior experience, however we typically only take in new regular members at the beginning of every term. This is to ensure that we are able to help all members progress further, together, each session. So look out for your introductory sessions!

**Training / Meeting Timings**
Multi-Purpose Hall (Block 57, Level 2)

_[Recreational]_ Wednesday 7-9pm (feel free to leave earlier)
_[Coached]_ Tuesday 8-10pm and/or Friday 3-5pm

**Student Organisation Introduction Video**
[SUTD Archery - DiscoverSUTD Video](https://youtu.be/yz5xHzGCEt0)

**Name / Contact of President**
Tan Le Xuan
Telegram: https://t.me/sorahawk
Email: lexuan_tan@mymail.sutd.edu.sg

**Other Relevant Links**
Telegram Group: https://t.me/joinchat/HpEyZo15F54yODI1
Instagram: https://www.instagram.com/sutd_archery/
Email: archery@club.sutd.edu.sg

**Comment by ExtremelySunnyYK** [comment]
Hi @Sorahawk  , thanks for submitting your fifthrow proposal!

Just wanted to get a bit more detail from you so that we can provide more precise information.

Could you provide the location/locations of the session in the proposal (add in with edit)?

Thank you!

**Comment by Sorahawk** [comment]
Hi @ExtremelySunnyYK, I have updated the post with our venue. Side note, we are currently working on a new intro video, I will update the URL before 16/8!
