### ISSUE TITLE
SUTD FOOTBALL INTRODUCTORY SESSION

### ISSUE THREAD

**Issue by sutdfootball** [OpenSUTD/DiscoverSUTD-2021-microsite#7]
**Name of Student Organisation***
[SUTD FOOTBALL]

**Cluster**
[Sports]

**Classification**
[Ffith Row]

**Description**
[Insert a short description of your Student Organisation, Less than 100 words]

**Training / Meeting Timings**
[Tuesdays and Thursdays 8.00pm-10.00pm]

**Student Organisation Introduction Video**
[link:]

**Name / Contact of President**
[Mohammed Fauzaan / @fauzxan]

**Other Relevant Links**
[Football Freshies Telegram Group: https://t.me/joinchat/76R66ryT17E1YjY1
Instagram: @fcsutd
Tiktok: @fcsutd]

**Comment by ExtremelySunnyYK** [comment]
Closed due to duplicate
