### ISSUE TITLE
SUTD FOOTBALL 

### ISSUE THREAD

**Issue by sutdfootball** [OpenSUTD/DiscoverSUTD-2021-microsite#8]
**Name of Student Organisation***
SUTD FOOTBALL

**Cluster**
Sports

**Classification**
Fifth Row

**Description**
We are a family of recreational and competitive players who just want to have fun while sharing our love for football. We welcome anyone who is willing to learn and be part of a team, regardless of experience. Our competitive players can also engage in competitions like Singapore University Games and Diva La Futbol

**Training / Meeting Timings**
Tuesdays and Thursdays 8.00pm-10.00pm

**Student Organisation Introduction Video**
[link: [https://youtu.be/xtopsha_OUI](url)

**Name / Contact of President**
Mohammed Fauzaan [https://t.me/fauzxan](url)

**Other Relevant Links**
[Football Freshies Telegram Group: [https://t.me/joinchat/76R66ryT17E1YjY1](url)
Instagram: [https://www.instagram.com/fcsutd](url)
Tiktok: [https://vt.tiktok.com/ZSJpLS5pr/](url)

**Comment by ExtremelySunnyYK** [comment]
This is great!
