### ISSUE TITLE
EV Club Introductory Session

### ISSUE THREAD

**Issue by woemwoem** [OpenSUTD/DiscoverSUTD-2021-microsite#82]
**Session Name**
EV Club Introductory Session

**Abstract**

Welcome to SUTD EV Club, where we explore all things electric vehicle! This introductory session hopes to give participants a glimpse of what it means to be an EV Club member and the exciting opportunities that await. 

Get to meet our current EXCO who will be sharing what you can expect when joining EV Club and the pathway to building your own EV. There will also be presentations by our project team leads who will be sharing what they are currently working on. 

**Student Organisation organising this session**
EV Club

**Event Format**
Physical with option to tune in virtually via Microsoft Teams.

Teams Link:
https://teams.microsoft.com/l/meetup-join/19%3ameeting_MjBiMjE1MTUtOWZlMy00YzFkLWFkMjMtODEyZDQ0ZTAwYTg2%40thread.v2/0?context=%7b%22Tid%22%3a%223476b776-e990-4f72-b950-62489831623d%22%2c%22Oid%22%3a%228ed069e1-f333-41c6-8628-e0254d315415%22%7d

**Session intent (what to expect)**

- Overview of EV Club and history
- EV Club current projects
- What to expect when joining EV Club
- Upcoming workshops
- Sharing from EV Club alumni
- Q&A

**Session details**

Session will be held in a Thinktank 24, up to 30 participants excluding EV Club members. The session will also be streamed on Microsoft Teams and recorded. 

**Speakers/Workshop facilitators**

Joshua Kwan - EV Club President
Matthew Wong - EV Club Vice President

Project Leads: 
Ishan - Shell Eco Marathon EV Conversion
Akhil - Shell Eco Marathon Aesthetic Upgrades

EV Club Alumni: 
Nigel Gomez - EVAM (3D Printed Car) team lead
Tan Kai Jie - Maker Rep

**Sign up link(if any)**
https://forms.office.com/r/cgprAhxy03

**Logistical details / Budget Needed**

No budget needed.
Require booking of Thinktank 24

**Comment by ExtremelySunnyYK** [comment]
Hi @woemwoem , thanks for submitting your event proposal!

Just wanted to get a bit more detail from you so that we can increase the chances of your event getting approved.

1. Could you provide an estimated number of attendees and how you would be able to ensure SHM if it was physical?
2. What is the exact date and timing for the booking of the location?

Thank you!

**Comment by woemwoem** [comment]
Sorry for the late reply. 

1. Estimated 40 attendees. If possible booking of both thinktank 24 and 25. (I believe they are connecting). Masks to be worn at all times. Participants to be seated individually. No interaction between participants other than Q and A in which masks will be worn.
2. Booking date and time: 22/9/21 1600-2000.

**Comment by castlemas** [comment]
> Sorry for the late reply.
> 
> 1. Estimated 40 attendees. If possible booking of both thinktank 24 and 25. (I believe they are connecting). Masks to be worn at all times. Participants to be seated individually. No interaction between participants other than Q and A in which masks will be worn.
> 2. Booking date and time: 22/9/21 1600-2000.

@woemwoem 

Is this correct?
Total attendees = 10 facils + 30 participants?

Would be great if you could let me know soon.

Thankyouxx

**Comment by woemwoem** [comment]
1. Physical Participants: 40
    Facilitators: 10
    Total: 50 Physical attendees. 
    Sorry for being unclear.

2. We are ok with shifting the session back. To confirm, the session would be from 6pm to 8pm. If possible, we would like to book the venue an hour earlier and an hour later to prepare and clean up. Ideally the venue could be booked from 5pm to 9pm.

**Comment by jolow99** [comment]
Hey @woemwoem , noted on your requested requirements. We will do our best to help you get a venue that fits your needs and will update you when we get the booking confirmation.

Could you please update your registration form to reflect the new timings, and put the venue as TBC first

**Comment by jolow99** [comment]
Dear @woemwoem   Your event has been approved by the school admin. 

The venue you have been allocated is TT9 and TT10 on 22 Sep 5pm - 8pm. Do remember to update your registration form with the venue as well. 

Wishing you a smooth and successful event!
