### ISSUE TITLE
SUTD CyclingGeng

### ISSUE THREAD

**Issue by unclerogercolander** [OpenSUTD/DiscoverSUTD-2021-microsite#87]
**Name of Student Organisation***
SUTD CyclingGeng

**Cluster**
Sports

**Classification**
Interest Group

**Description**
SUTD CyclingGeng is home to some of the loosest, fastest, most fun-loving fellas around that just plain love cycling. From clocking 100K round-islands in crocs, blasting through janky mountain-biking trails, to chasing those Strava KOMs/PRs through TMCR, we may go flat out some days (because we have no pacing strategy... yet) but we sure have a good time all days. Grab your bike, grow with our family, ride your best life. Regardless if you are a dyed-in-the-wool aero machine, hyper-technical mountain biker, PCN warrior or somewhere in-between, as long as you love cycling, CyclingGeng may just be your ride. 

**Training / Meeting Timings**
**‼️ You MUST bring your own bike !!**
Race calendar (road racing team): Mondays, Wednesdays and Fridays 6.30pm-8.30pm
Alt calendar: TBC
(Being a young IG a lot of these details are still work in progress, don't worry too much about it for now. What's crucial is your love of cycling! Bear with us as we work these details out along the way :) )

**Student Organisation Introduction Video**
NA

**Name / Contact of President**
Timothy Wee - President 
timothy_wee@mymail.sutd.edu.sg 
@weeotim

Lim Fuo En - Treasurer/2IC
fuoen_lim@mymail.sutd.edu.sg
@FeMan1999

**Other Relevant Links**
Website: https://sutdcyclinggeng.carrd.co/

**Comment by ExtremelySunnyYK** [comment]
Hey @unclerogercolander thanks for submitting the student club details for cyclinggeng! Pretty cool.

This is good.

**Comment by unclerogercolander** [comment]
> Hey @unclerogercolander thanks for submitting the student club details for cyclinggeng! Pretty cool.
> 
> This is good.

thanks for your work bro, appreciate it :)
- Tim

**Comment by ExtremelySunnyYK** [comment]
@unclerogercolander approved! thank you and all the best for the event!
