### ISSUE TITLE
Mechanical Designer Club Short Introductory Session

### ISSUE THREAD

**Issue by robobdo** [OpenSUTD/DiscoverSUTD-2021-microsite#95]
**Session Name**
MechD Short Online Introduction

**Abstract**
How do we design practical parts/ components? How do we know if the parts will look good?

CAD software allow us to create and visualise our designs in a virtual environment, before 3D printing or fabricating the models.

Interested to learn more? MechD club provides beginner to intermediate workshops for SolidWorks and Fusion360, as well as CAD related events and certifications.

**Student Organisation organising this session**
Mechanical Designer Club

**Event Format**
Virtual on MS Teams (link will be sent to registered participants).

**Session intent (what to expect)**
- Introduction to MechD
- Brief explanation of CAD and how the software enables good design practices
- Past MechD events
- Upcoming MechD events
- EXCO roles and responsibilities for those interested in taking on leadership opportunities
- Q&A

**Session details**
Date: 16 September 2021
Time: 9.00pm to 10.00pm
Up to 50 participants online, can be adjusted for larger capacity.

**Speakers/Workshop facilitators**
Brendan Ong, President
Akshaya Maddula, Vice President     
Artiaga Samantha, Treasurer
Joshua Lim, Secretary
Chew Yoong Hao, SolidWorks Programme Director
Keane Hi, Fusion360 Programme Director
Claudia Lai, Publicity Director

**Sign up link(if any)**
https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPRLkhYYN7CJBlLXVXUDbKexURUhSUkFRQ1RVUlgyQ1o1VklEQzdPRkVUQy4u

**Logistical details / Budget Needed**
No budget required.

mech_d@club.sutd.edu.sg

**Comment by jolow99** [comment]
Dear @robobdo  Your event has been approved by the school admin. 

Wishing you a smooth and successful event!
