### ISSUE TITLE
Design Odyssey 1st Workshop Session – Introduction & Induction to Design Innovation Workshop

### ISSUE THREAD

**Issue by issacj-17** [OpenSUTD/DiscoverSUTD-2021-microsite#96]
**Session Name**
Design Odyssey: Introduction to Design Innovation

**Abstract**
Learn all about Design Odyssey’s DRIVE programme. The session includes a Design Innovation exercise, where students will learn design innovation and technical skills that are highly in-demand by the workforce.

**Student Organisation organising this session**
Design Odyssey

**Event Format**
Virtual (Zoom)

**Session intent (what to expect)**
- Participants will learn about _Design Odyssey’s DRIVE programme_, and the opportunities available to them to _Discover, Define, Develop and Deliver their self-initiated Social Innovations from Ideation to Business Pitching_.
- Sharing with Past Participants and their start-up success!
- Students will get a chance to participate in a _Micro Design Innovation exercise_, where they will learn _design innovation_ and _technical skills_ that are highly in-demand by the workforce.

**Session details**
Date: 17 September 2021 (Friday)
Time: 3 pm to 5.30 pm (please log in 10 mins prior to the start of the session)
Venue: Zoom (details will be provided closer to the date of the event.)
Number of participants: Max. 60

**Speakers/Workshop facilitators**
Ms. Sio Lim, Associate Program Director, Design Odyssey, SUTD International Design Centre (IDC)
Ms. Ashreya M Venkatesh, Design Engineer, Design Odyssey, SUTD International Design Centre (IDC)
Mr. Vaughn Chandra Oliver, Design Engineer, Design Odyssey, SUTD International Design Centre (IDC)
DO Student EXCO members

**Sign up link**
Link to Form: https://forms.office.com/r/imLP3hmRJy
Club’s Email Address: design_odyssey@sutd.edu.sg

**Logistical details / Budget Needed**
$100 for Ugly Food ice cream vouchers for participants.

**Comment by ExtremelySunnyYK** [comment]
Hey @issacj-17 thanks for submitting the event proposal for the introductory session for DO.

Could you kindly provide us with the budget breakdown? For instance how many ice cream vouchers would you be getting?

Do note to keep the receipts as it would be required for claims in concur.

Thank you!

**Comment by issacj-17** [comment]
Hey @ExtremelySunnyYK

**Comment by issacj-17** [comment]
Hey @ExtremelySunnyYK 

Our budget breakdown is based on the assumption that we will have 50 participants (based on experience from past workshops). We would like to offer every participant the opportunity to consume an Ugly Food ice-cream. We estimate the cost to be $2 per pax.

In other words, it would be 50 x $2 (= $100) for each of the 3 sessions.

Also, do you need me to replicate the above for the 3 issues on GitHub?

**Comment by ExtremelySunnyYK** [comment]
Thank you. nope the comment does not have to be replicated.

**Comment by jolow99** [comment]
Dear @issacj-17 Your event has been approved by the school admin. 

Additionally, your budget request of $100 for workshop 1 has been allocated $50. Meaning that you have a total budget allocation of $100 across your two events. 

Wishing you a smooth and successful event!

**Comment by issacj-17** [comment]
Thanks @jolow99. Will relay it back to my team.
