### ISSUE TITLE
Design Odyssey 2nd Workshop Session – Introduction & Induction to Business 360 Workshop

### ISSUE THREAD

**Issue by issacj-17** [OpenSUTD/DiscoverSUTD-2021-microsite#97]
**Session Name**
Design Odyssey: Introduction to Business 360

**Abstract**
Learn all about Design Odyssey’s DRIVE programme. The session includes Business Model exercise, where students will learn how to leverage on the Business model canvas as a strategic and management tool to describe, design and pivot a business!

**Student Organisation organising this session**
Design Odyssey

**Event Format**
Virtual (Zoom)

**Session intent (what to expect)**
- Participants will learn about _Design Odyssey’s DRIVE programme_, and the opportunities available to them to _Discover, Define, Develop and Deliver their self-initiated Social Innovations from Ideation to Business Pitching_.
- Sharing with Past Participants and their start-up success!
- Students will get a chance to participate in a _Business Model exercise_, where they will learn how to _leverage on the Business model canvas_ as a strategic and management tool to describe, design and pivot a business.

**Session details**
Date: 24 September 2021 (Friday)
Time: 3 pm to 5.30 pm (please log in 10 mins prior to the start of the session)
Venue: Zoom (details will be provided closer to the date of the event.)
Number of participants: Max. 60

**Speakers/Workshop facilitators**
Ms. Sio Lim, Associate Program Director, Design Odyssey, SUTD International Design Centre (IDC)
Ms. Ashreya M Venkatesh, Design Engineer, Design Odyssey, SUTD International Design Centre (IDC)
Mr. Vaughn Chandra Oliver, Design Engineer, Design Odyssey, SUTD International Design Centre (IDC)
DO Student EXCO members

**Sign up link**
Link to Form: https://forms.office.com/r/imLP3hmRJy
Club’s Email Address: design_odyssey@sutd.edu.sg

**Logistical details / Budget Needed**
$100 for Ugly Food ice cream vouchers for participants.

**Comment by ExtremelySunnyYK** [comment]
Hey @issacj-17 thanks for submitting the event proposal for the introductory session for DO.

Could you kindly provide us with the budget breakdown? For instance how many ice cream vouchers would you be getting?

Also would the budget for ice cream vouchers be shared among the 3 sessions?


Thank you!

**Comment by jolow99** [comment]
Dear @issacj-17 Your event has been approved by the school admin. 

Additionally, your budget request of $100 for workshop 2 has been allocated $50. Meaning that you have a total budget allocation of $100 across your two events. 

Wishing you a smooth and successful event!
