### ISSUE TITLE
Design Odyssey 3rd Workshop Session – Introduction & Ideation Workshop

### ISSUE THREAD

**Issue by issacj-17** [OpenSUTD/DiscoverSUTD-2021-microsite#98]
**Session Name**
Design Odyssey: Introduction & Ideation

**Abstract**
Learn all about Design Odyssey’s DRIVE programme. The session includes Ideation exercise, where students will learn about Ideation Mindset, Methods and Down Selection Tools!

**Student Organisation organising this session**
Design Odyssey

**Event Format**
Virtual (Zoom)

**Session intent (what to expect)**
- Participants will learn about _Design Odyssey’s DRIVE programme_, and the opportunities available to them to _Discover, Define, Develop and Deliver their self-initiated Social Innovations from Ideation to Business Pitching_.
- Sharing with Past Participants and their start-up success!
- Students will get a chance to participate in an _Ideation exercise_, where they will _learn about Ideation Mindset, Methods and Down Selection Tools!_

**Session details**
Date: 1 October 2021 (Friday)
Time: 3 pm to 5.30 pm (please log in 10 mins prior to the start of the session)
Venue: Zoom (details will be provided closer to the date of the event.)
Number of participants: Max. 60

**Speakers/Workshop facilitators**
Ms. Sio Lim, Associate Program Director, Design Odyssey, SUTD International Design Centre (IDC)
Ms. Ashreya M Venkatesh, Design Engineer, Design Odyssey, SUTD International Design Centre (IDC)
Mr. Vaughn Chandra Oliver, Design Engineer, Design Odyssey, SUTD International Design Centre (IDC)
DO Student EXCO members

**Sign up link**
Link to Form: https://forms.office.com/r/imLP3hmRJy
Club’s Email Address: design_odyssey@sutd.edu.sg

**Logistical details / Budget Needed**
$100 for Ugly Food ice cream vouchers for participants.

**Comment by issacj-17** [comment]
Okay, thanks @makehahaz. 

In that case, we require no budget for our 3rd workshop from the DiscoverSUTD Committee. My team will find an alternative to fund this workshop.

**Comment by ExtremelySunnyYK** [comment]
Thank you for your understanding Issac!
